### ISSUE TITLE
Meaning of relation is_on() in location.py

### ISSUE THREAD

**Issue by navdeepkjohal** [azreasoners/LLM-ASP#2]
Dear Authors,

I have one question for you. Could you please explain the meaning of is_on() relation at the following line of asp_module/location.py:

https://github.com/azreasoners/LLM-ASP/blob/357d469d6f76afe46e9ea21c2f71d27a88f471cc/asp_modules/location.py#L48

Or is it really a typo and it was meant to be written as is( ) relation?

Best regards,
Navdeep

**Comment by AdamIshay** [comment]
Hello,

Thank you for pointing this out! Indeed this should be written as is( ), meaning A and B be have a spatial relation, designated by "Kind".
